name: ci

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          export PATH=$HOME/.cargo/bin:$PATH
      - name: Test backend
        working-directory: rusty_backend
        run: |
          cargo check
          cargo test -- --test-threads=1
      - name: Test frontend
        working-directory: rusty_frontend
        run: |
          cargo check