name: ci

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test backend
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          export PATH=$HOME/.cargo/bin:$PATH
          cd rusty_backend
          cargo check
          cargo test -- --test-threads=1